// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuemaczkeofhcalrtnaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZW1hY3prZW9maGNhbHJ0bmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODk0NDcsImV4cCI6MjA2MDU2NTQ0N30.ehikmvSz2GSV4LBhlR5buwVyq8ioKoYllHGnYgYU5VI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);